const contenu = [
    {
        index: 0,
        name: "sweets",
        libelle : "sweet item",
        url: "img/sweets-1.jpeg",
        prix : 5,
        vote :-1
    },
    {
        index: 1,
        name: "cupcakes",
        libelle : "cupcake item",
        url: "img/cupcake-1.jpeg",
        prix : 5,
    },
    {
        index: 2,
        name: "cakes",
        libelle : "cake item",
        url: "img/cake-1.jpeg",
        prix : 5,
    },
    {
        index: 3,
        name: "dougnuts",
        libelle : "dougnut item",
        url: "img/doughnut-1.jpeg",
        prix : 5,
    },
    {
        index: 4,
        name: "sweets",
        libelle : "sweet item",
        url: "img/sweets-2.jpeg",
        prix : 10,
    },
    {
        index: 5,
        name: "cupcakes",
        libelle : "cupcake item",
        url: "img/cupcake-2.jpeg",
        prix : 10,
    },
    {
        index: 6,
        name: "cakes",
        libelle : "cake item",
        url: "img/cake-2.jpeg",
        prix : 10,
    },
    {
        index: 7,
        name: "dougnuts",
        libelle : "dougnut item",
        url: "img/doughnut-2.jpeg",
        prix : 10,
    },
    {
        index: 8,
        name: "sweets",
        libelle : "sweet item",
        url: "img/sweets-3.jpeg",
        prix : 15,
    },
    {
        index: 9,
        name: "cupcakes",
        libelle : "cupcake item",
        url: "img/cupcake-3.jpeg",
        prix : 15,
    },
    {
        index: 10,
        name: "cakes",
        libelle : "cake item",
        url: "img/cake-3.jpeg",
        prix : 15,
    },
    {
        index: 11,
        name: "dougnuts",
        libelle : "dougnut item",
        url: "img/doughnut-3.jpeg",
        prix : 15,
    },
]